### ISSUE TITLE
flight_event flight phase duration ORM calculator

### ISSUE THREAD

**Issue by annzzu** [smartops-aero/smartops-odoo-flight#1]
- use ORM methods and logics to calculate flight duration instead of SQL queries

**Comment by ayushin** [comment]
@annzzu What do you think about this solution? https://github.com/smartops-aero/smartops-odoo-flight/pull/4 

Can you improve it further to ensure it scales into 10s of million of records?

**Comment by annzzu** [comment]
When handling millions of records, using a `One2many` field is a better option than a `Json` field. `One2many` makes it easier to search, sort, and manage big amounts of data because it fits naturally with how databases work. It also helps keep the data clean and accurate with built-in rules, and it’s simple to make changes as needed.

In comparison, `Json` fields aren’t as good for large amounts of data because they can’t be searched or sorted as easily, which can slow things down. `One2many` fields also handle many users and updates at the same time much better, making sure the system runs smoothly even when lots of people are using it.

**Comment by annzzu** [comment]
I used store=True in the One2many field for flight.phase.duration so that the calculated values are saved in the database. This makes things faster because it avoids recalculating the values every time you need them, which is really helpful when dealing with millions of records.

If I had used store=False, the values would be recalculated each time you check them, which can slow things down, especially with large data. Saving the values in the database reduces the server’s workload and speeds up performance. Making the model transient (temporary) would cause similar slowdowns since the data wouldn’t be saved and would need constant recalculating.

**Comment by ayushin** [comment]
allright, can you make a PR to the existing code so we handle all sort of durations, not only 'a' as in your previous pull request?
